project:
  group: laplacian
  name: model.project
  type: model
  namespace: laplacian
  version: '1.0.0'
  source_repository:
    url: https://github.com/nabla-squared/laplacian.model.project.git
    branch: master
  subprojects: []
  schemas: []
  templates: []
  model_files: []
  template_files: []
