project:
  group: laplacian
  name: project.schema-model
  type: model
  namespace: laplacian.project
  version: '1.0.0'
  description: |
    A model which expresses the logical structure of laplacian-based projects and modules.
  source_repository:
    url: https://github.com/nabla-squared/laplacian.project.schema-model.git
    branch: master
  subprojects: []
  schemas: []
  plugins:
  - group: laplacian
    name: metamodel-plugin
    version: '1.0.0'
  - group: laplacian
    name: project.schema-plugin
    version: '1.0.0'
  templates:
  - group: laplacian
    name: project.base-template
    version: '1.0.0'
  - group: laplacian
    name: schema.document-template
    version: '1.0.0'
  models:
  - group: laplacian
    name: project.document-content
    version: '1.0.0'
  model_files:
  - src/
  template_files: []
