project:
  group: laplacian
  name: project.schema-model
  type: domain-model
  namespace: laplacian.project
  version: '1.0.0'
  description:
    en: |
      This model represents the logical structure of a *Laplacian*-based project.
    ja: |
      このモデルは*Laplacian*プロジェクトの論理構造を表します。
    zh: |
      该模型代表了*Laplacian*项目的逻辑结构。
  source_repository:
    url: https://github.com/nabla-squared/laplacian.project.schema-model.git
    branch: master
  plugins:
  - group: laplacian
    name: common-model-plugin
    version: '1.0.0'
  models:
  - group: laplacian
    name: common-model
    version: '1.0.0'
  model_files:
  - dest/
