project:
  group: laplacian
  name: project.domain-model-plugin
  type: domain-model-plugin
  namespace: laplacian.project
  version: '1.0.0'
  description:
    en: |
      A domain model plugin module for the project.domain-model.
    ja: |
      project.domain-model のドメインモデルプラグインモジュール
    zh: |
      project.domain-model 域模型插件模块
  module_repositories:
    local:
      ../../../../../mvn-repo
    remote:
    - https://github.com/nabla-squared/mvn-repo
  plugins:
  - group: laplacian
    name: common-model-plugin
    version: '1.0.0'
  models:
  - group: laplacian
    name: project.domain-model
    version: '1.0.0'
  - group: laplacian
    name: common-model
    version: '1.0.0'
