entities:
- name: project
  namespace: laplacian.project
  singly_rooted: true

  properties:
  - name: group
    type: string
    primary_key: true

  - name: name
    type: string
    primary_key: true

  - name: type
    type: string
    optional: true
    default_value: |
      "generator"

  - name: author
    type: string
    optional: true

  - name: licensor
    type: string
    optional: true
    default_value: |
      author

  - name: license
    type: string
    optional: true
    domain:
      choices:
      - value: MIT
      - value: Apache2.0
      - value: Closed

  - name: role
    type: string
    snippet: |
      projectType.role

  - name: version
    type: string

  - name: namespace
    type: string
    optional: true
    default_value: |
      listOf(group, name)
          .map{ it.lowerUnderscorize() }
          .joinToString(".")
    example_values:
    - "laplacian.model.metamodel"

  - name: model_files
    type: string
    multiple: true
    optional: true

  - name: template_files
    type: string
    multiple: true
    optional: true

  - name: base_dir
    type: string
    optional: true
    default_value: |
      "subprojects/${name.lowerHyphenize()}"
    example_values:
    - "subprojects/laplacian.model.metamodel"

  - name: is_model
    type: boolean
    snippet: |
      role == "model"

  - name: is_template
    type: boolean
    snippet: |
      role == "template"

  - name: is_plugin
    type: boolean
    snippet: |
      role == "plugin"

  - name: is_domain_model
    type: boolean
    snippet: |
      type == "domain-model"

  - name: is_domain_model_plugin
    type: boolean
    snippet: |
      type == "domain-model-plugin"

  - name: sources
    type: string
    multiple: true

  relationships:
  - name: description
    reference_entity_name: multilingual_text
    reference_entity_namespace: laplacian.common
    cardinality: '0..1'
    aggregate: true

  - name: project_type
    reference_entity_name: project_type
    cardinality: '1'
    mappings:
    - from: type
      to: name

  - name: parent_project
    reference_entity_name: project
    cardinality: '0..1'
    reverse_of: subprojects

  - name: subprojects
    reference_entity_name: project
    cardinality: '*'
    aggregate: true

  - name: source_repository
    reference_entity_name: source_repository
    cardinality: '0..1'
    aggregate: true

  - name: module_repositories
    reference_entity_name: module_repository_list
    cardinality: '0..1'
    aggregate: true

  - name: document
    reference_entity_name: document
    cardinality: '0..1'
    aggregate: true

  - name: scripts
    reference_entity_name: script
    cardinality: '*'
    aggregate: true

  - name: models
    reference_entity_name: module
    cardinality: '*'
    aggregate: true

  - name: templates
    reference_entity_name: module
    cardinality: '*'
    aggregate: true

  - name: plugins
    reference_entity_name: module
    cardinality: '*'
    aggregate: true

  - name: all_models
    reference_entity_name: module
    cardinality: '*'
    snippet: |
      (projectType.allModels + models).distinctBy{ "${it.group}:${it.name}" }

  - name: all_templates
    reference_entity_name: module
    cardinality: '*'
    snippet: |
      (projectType.allTemplates + templates).distinctBy{ "${it.group}:${it.name}" }

  - name: all_plugins
    reference_entity_name: module
    cardinality: '*'
    snippet: |
      (projectType.allPlugins + plugins).distinctBy{ "${it.group}:${it.name}" }
