project:
  sources:
  - "README.md"
  - "doc/entities/DocumentChapter.md"
  - "doc/entities/Document.md"
  - "doc/entities/Module.md"
  - "doc/entities/ProjectType.md"
  - "doc/entities/Project.md"
  - "doc/entities/Section.md"
  - "doc/entities/SourceRepository.md"
  - "doc/image/model-diagram.svg"
  - ".editorconfig"
  - ".gitattributes"
  - ".gitignore"
  - "model/project/sources.yaml"
  - "model/project.yaml"
  - "src/entities/laplacian/document_section.yaml"
  - "src/entities/laplacian/document.yaml"
  - "src/entities/laplacian/module.yaml"
  - "src/entities/laplacian/project/examples.yaml"
  - "src/entities/laplacian/project_type.yaml"
  - "src/entities/laplacian/project.yml"
  - "src/entities/laplacian/source_repository.yaml"
